# Generated by Django 5.1.6 on 2025-02-08 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('customer_type', models.CharField(choices=[('existing', 'Existing Customer'), ('new', 'New Customer')], max_length=10)),
                ('bank_name', models.CharField(choices=[('hdfc', 'HDFC Bank'), ('sbi', 'State Bank of India'), ('icici', 'ICICI Bank'), ('axis', 'Axis Bank'), ('pnb', 'Punjab National Bank')], max_length=50)),
                ('account_number', models.CharField(max_length=20)),
                ('complaint_type', models.CharField(choices=[('transaction', 'Transaction Issue'), ('account', 'Account Problem'), ('service', 'Service Complaint'), ('fraud', 'Fraud Report'), ('other', 'Other')], max_length=20)),
                ('complaint_title', models.CharField(max_length=200)),
                ('complaint_description', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
