# Generated by Django 5.1.5 on 2025-02-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='account_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Under Process', 'Under Process'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
