# Generated by Django 5.1.5 on 2025-02-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_alter_complaint_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
