# Generated by Django 5.1.6 on 2025-02-22 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_complaint_resolved_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='resolved_at',
        ),
    ]
