# Generated by Django 5.1.6 on 2025-02-25 09:35

import complaint.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0005_complaint_resolved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='track_id',
            field=models.CharField(default=complaint.models.generate_trackid, editable=False, max_length=20, unique=True),
        ),
    ]
