# Generated by Django 5.1.6 on 2025-02-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0006_alter_complaint_track_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='track_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
