# Generated by Django 5.1.6 on 2025-02-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0007_alter_complaint_track_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='bank_name',
        ),
    ]
