# Generated by Django 5.1.6 on 2025-02-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0009_complaint_bank_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='bank_name',
        ),
    ]
