# Generated by Django 5.1.5 on 2025-02-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='Username',
            field=models.CharField(default='default_username', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='password',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
