# Generated by Django 5.1.5 on 2025-02-21 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_remove_staffprofile_user_staffprofile_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='role',
        ),
    ]
