# Generated by Django 5.1.6 on 2025-02-21 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_remove_staffprofile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofile',
            old_name='Username',
            new_name='username',
        ),
    ]
