# Generated by Django 5.1.6 on 2025-02-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_rename_username_staffprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
